name: Build and publish Docker image

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU (for multi-platform builds)
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/memory-mcp:latest
            ghcr.io/${{ github.repository_owner }}/memory-mcp:${{ github.sha }}

      - name: Upload image tag as artifact
        uses: actions/upload-artifact@v4
        with:
          name: image-tags
          path: |
            ./

  smoke-test:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull built image
        run: |
          docker pull ghcr.io/${{ github.repository_owner }}/memory-mcp:latest

      - name: Create docker network
        run: |
          docker network create smoke-net || true

      - name: Start MongoDB
        run: |
          docker run -d --name smoke-mongo --network smoke-net -p 27017:27017 mongo:6.0

      - name: Start memory-mcp app
        run: |
          docker run -d --name smoke-memory-mcp --network smoke-net -p 3000:3000 -e MONGODB_URI="mongodb://smoke-mongo:27017/memorydb" ghcr.io/${{ github.repository_owner }}/memory-mcp:latest

      - name: Wait for app to be reachable
        run: |
          for i in {1..20}; do
            if curl -sSf http://localhost:3000/mcp/tools >/dev/null 2>&1; then
              echo "app is up"; exit 0; fi
            sleep 3
          done
          echo "app did not become ready"; exit 1

      - name: Run Python smoke-test
        run: |
          python3 -m pip install -r scripts/requirements.txt
          python3 scripts/test_discovery.py --url http://localhost:3000

      - name: Tear down smoke containers
        if: always()
        run: |
          docker rm -f smoke-memory-mcp || true
          docker rm -f smoke-mongo || true